### ISSUE TITLE
Usage with i18next

### ISSUE THREAD

**Issue by martijnmichel** [box/mojito#685]
Can I use mojito with i18next json files?

**Comment by aurambaj** [comment]
@martijnmichel I haven't used `i18next` but the `JSON` format seems pretty standard and match with what [Mojito supports](https://www.mojito.global//docs/refs/mojito-file-formats/#json). 

I see [i18next has support for plural strings](https://www.i18next.com/translation-function/plurals) and that won't be supported with the default JSON. Mojito only [support plural in PO, android and IOS files](https://www.mojito.global//docs/guides/plural-support/).

**Comment by matzeeable** [comment]
Hey @martijnmichel and @aurambaj !

Did you get it to manage? My folder structure for `i18next` extracted strings looks like this:

![image](https://user-images.githubusercontent.com/1008534/122952462-53311e00-d37e-11eb-9588-1ee41f9e8fc5.png)

And if I try to push the `locale` folder with `-l "(de)->de_DE"` I am getting the following error:

```
Locale [de] does not exist in the system
```

Is there a solution for this? Or do I need to force 4-letter codes?

**Comment by martijnmichel** [comment]
Nope, decided to use weblate.

**Comment by aurambaj** [comment]
@matzeeable local mapping should look use `-lm` for example `mojito pull -r MyRepo -lm "de:de-DE,es:es-ES,fr:fr-FR,ja:ja-JP"` see here: see https://www.mojito.global//docs/guides/generating-localized-files/#locale-mapping. It is an option for `pull` and `import` (not `push` so not sure what command you are trying to run exactly).

If you're running the latest Mojito from the master you can have either tag: "de" or "de-DE" but it must be specified accordingly when creating the repository and then used as defined. (the last release is old and as far as I remember doesn't contain the locales with 2 letters only so if you using that you'd have to use mapping for sure)

**Comment by aurambaj** [comment]
Assuming you rename the file, the basic commands to get started would look like: 

```bash
root@e52b9e000475:/tmp/i18nnext/locale# find .
.
./translation.json
./translation_fr.json
root@e52b9e000475:/tmp/i18nnext/locale# cat translation.json
{
	"hello" : "Hello!"
}
root@e52b9e000475:/tmp/i18nnext/locale# cat translation_fr.json
{
	"hello" : "Bonjour!"
}
root@e52b9e000475:/tmp/i18nnext/locale# mojito repo-create -n i18nnext -l de fr
Create repository: i18nnext
Extracting locale: de
Extracted RepositoryLocale:
-- bcp47Tag = de
-- isFullyTranslated = true
Extracting locale: fr
Extracted RepositoryLocale:
-- bcp47Tag = fr
-- isFullyTranslated = true

created --> repository id: 3
root@e52b9e000475:/tmp/i18nnext/locale# mojito push -r i18nnext -ft JSON

Push assets to repository: i18nnext

 - Uploading: translation.json
 --> asset id: 3, task: 23

Running, task id: 23
Creating asset: translation.json (24) Done
Process asset content, id: 3 (25) Done
  Extracting text units from asset (26) Done
  Create new text units (27) Done
  Updating branch asset text units (29) Done
  Updating merged asset text units (30) Done
  Perform leveraging (31) Done

Finished

root@e52b9e000475:/tmp/i18nnext/locale# cp translation.json translation_de.json
root@e52b9e000475:/tmp/i18nnext/locale# mojito import -r i18nnext -ft JSON

Start importing localized files for repository: i18nnext

 - Importing file: /tmp/i18nnext/locale/translation_fr.json

Running, task id: 34
ImportLocalizedAssetJob (34) Done
 - Importing file: /tmp/i18nnext/locale/translation_de.json

Running, task id: 35
ImportLocalizedAssetJob (35) Done

Finished

root@e52b9e000475:/tmp/i18nnext/locale# mojito pull -r i18nnext -ft JSON

Pull localized asset from repository: i18nnext

Localizing: translation.json
 - Processing locale: de --> translation_de.json
 - Processing locale: fr --> translation_fr.json

Finished

root@e52b9e000475:/tmp/i18nnext/locale# cat translation_de.json
{
	"hello" : "Hallo!"
}
```

**Comment by matzeeable** [comment]
Hey @aurambaj !

Thanks for your awesome response and for taking the time.

Yeah, you are right, if we can change the folder structure, we could go that way. I need to talk with my developer colleague and will let you know about results.

> If you're running the latest Mojito from the master you can have either tag: "de" or "de-DE" but it must be specified accordingly when creating the repository and then used as defined

Unfortunately I cannot use the latest release from `master` as I need to use `docker`. But I could not get the images in https://github.com/box/mojito/tree/master/docker to work, so I am using https://github.com/zuc/docker-mojito . You perhaps should consider adding / updating the `Dockerfile`.

Regards,
Matthew 😊

**Comment by aurambaj** [comment]
@matzeeable I did some cleanup to the docker files and docker compose recently (2 weeks ago) and it's been working for me on Mac and Ubuntu 18.04. Have you tried since then? And if yes, could you share the error you're getting?

**Comment by matzeeable** [comment]
@aurambaj I just tried to figure out how to use the docker images you mentioned, unfortunately I cannot find an updated version (last update 5 years ago): https://hub.docker.com/search?q=aurambaj&type=image

I think you need to push the latest build to the hub. Another question, do you also provide an image with the CLI only?

> I'd be interested to know if there is a de-facto standard for json files with i18n. If there is,

We are using this https://github.com/i18next/i18next-parser to extract texts from our source code. As "de-facto standard" I only see the [`output`](https://github.com/i18next/i18next-parser#options) configuration which produces the folder structure above.

What do you think?

**Comment by aurambaj** [comment]
Right I don't push images to docker hub on a regular basis, since I never really got the need for it. I build custom images for the current deployment I'm working on. 

I'd be interested to see how you would use the generic images actually. Where/how you deploy the app, configure the secrets, etc.

Using file in https://github.com/box/mojito/tree/master/docker you should be able to 

```
git clone git@github.com:box/mojito.git
cd docker
docker compose up
```

I'll add an docker file for the CLI only soon.

**Comment by matzeeable** [comment]
> Right I don't push images to docker hub on a regular basis [...]
> Pushed a dockerfile for a standalone CLI (built from source): https://github.com/box/mojito/pull/693/files

You should really consider pushing the built images to the docker hub. Unfortunately we cannot build the images ourselves as this is not part of our "codebase" (and should not be). It is best practice to rely on already pushed images and simply pull them instead of building them. What do you think? I see you are using GitHub Actions (I never used this before), but perhaps this is something you need so you can automate things: https://github.com/marketplace/actions/build-and-push-docker-images

> I'd be interested to see how you would use the generic images actually. Where/how you deploy the app [...]

We are currently using [`traefik`](https://github.com/traefik/traefik) to route our applications on our production server, but this is not relevant for this issue, I think. But here is the part of our `docker-compse.yml`:

```yaml
version: "3"

networks:
    mojito: {}
    traefik:
        external: true

volumes:
    mojito_mysql_data:

services:
#   Mojito Translation Repository (https://github.com/box/mojito/)

    mojito_owlsrv_de_mysql:
        image: mysql:5.7
        volumes:
            - mojito_mysql_data:/var/lib/mysql:rw
        restart: always
        networks:
            - mojito
            - traefik
        environment:
            MYSQL_ROOT_PASSWORD: ${MOJITO_DB_ROOT_PASS}
            MYSQL_DATABASE: mojito
            MYSQL_USER: ${MOJITO_DB_USER}
            MYSQL_PASSWORD: ${MOJITO_DB_PASS}
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_bin

    mojito_owlsrv_de_webapp:
        depends_on: [mojito_owlsrv_de_mysql]
        image: mzuccala/mojito:latest
        networks:
            - mojito
            - traefik
        restart: always
        environment:
            MOJITO_DB_HOST: mojito_owlsrv_de_mysql
            MOJITO_DB_PORT: 3306
            MOJITO_DB_NAME: mojito
            MOJITO_DB_USER: ${MOJITO_DB_USER}
            MOJITO_DB_PASS: ${MOJITO_DB_PASS}
```

> configure the secrets, etc.

As you can see, we are using variables inside our `docker-compose.yml`. This environment variables are exposed by [GitLab Variables](https://docs.gitlab.com/ee/ci/variables/#add-a-cicd-variable-to-a-project). So, you can imagine like this:

1. We have a CI/CD job `docker production start`
1. Within that job, all our secrets gets exposed to the shell via GitLab mechanism
1. We are running `docker-compose up` to start all containers

I hope this makes things clear. Please do not hesitate to ask further questions!
